# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dexer/Repos/cpp/competition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dexer/Repos/cpp/competition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dexer/Repos/cpp/competition/CMakeFiles /home/dexer/Repos/cpp/competition//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dexer/Repos/cpp/competition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code_craft

# Build rule for target.
code_craft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code_craft
.PHONY : code_craft

# fast build rule for target.
code_craft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/build
.PHONY : code_craft/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/main.cpp.s
.PHONY : main.cpp.s

src/debug.o: src/debug.cpp.o
.PHONY : src/debug.o

# target to build an object file
src/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/debug.cpp.o
.PHONY : src/debug.cpp.o

src/debug.i: src/debug.cpp.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/debug.cpp.i
.PHONY : src/debug.cpp.i

src/debug.s: src/debug.cpp.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/debug.cpp.s
.PHONY : src/debug.cpp.s

src/delete.o: src/delete.cpp.o
.PHONY : src/delete.o

# target to build an object file
src/delete.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/delete.cpp.o
.PHONY : src/delete.cpp.o

src/delete.i: src/delete.cpp.i
.PHONY : src/delete.i

# target to preprocess a source file
src/delete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/delete.cpp.i
.PHONY : src/delete.cpp.i

src/delete.s: src/delete.cpp.s
.PHONY : src/delete.s

# target to generate assembly for a file
src/delete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/delete.cpp.s
.PHONY : src/delete.cpp.s

src/extern.o: src/extern.cpp.o
.PHONY : src/extern.o

# target to build an object file
src/extern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/extern.cpp.o
.PHONY : src/extern.cpp.o

src/extern.i: src/extern.cpp.i
.PHONY : src/extern.i

# target to preprocess a source file
src/extern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/extern.cpp.i
.PHONY : src/extern.cpp.i

src/extern.s: src/extern.cpp.s
.PHONY : src/extern.s

# target to generate assembly for a file
src/extern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/extern.cpp.s
.PHONY : src/extern.cpp.s

src/interactions.o: src/interactions.cpp.o
.PHONY : src/interactions.o

# target to build an object file
src/interactions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/interactions.cpp.o
.PHONY : src/interactions.cpp.o

src/interactions.i: src/interactions.cpp.i
.PHONY : src/interactions.i

# target to preprocess a source file
src/interactions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/interactions.cpp.i
.PHONY : src/interactions.cpp.i

src/interactions.s: src/interactions.cpp.s
.PHONY : src/interactions.s

# target to generate assembly for a file
src/interactions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/interactions.cpp.s
.PHONY : src/interactions.cpp.s

src/read.o: src/read.cpp.o
.PHONY : src/read.o

# target to build an object file
src/read.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/read.cpp.o
.PHONY : src/read.cpp.o

src/read.i: src/read.cpp.i
.PHONY : src/read.i

# target to preprocess a source file
src/read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/read.cpp.i
.PHONY : src/read.cpp.i

src/read.s: src/read.cpp.s
.PHONY : src/read.s

# target to generate assembly for a file
src/read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/read.cpp.s
.PHONY : src/read.cpp.s

src/write.o: src/write.cpp.o
.PHONY : src/write.o

# target to build an object file
src/write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/write.cpp.o
.PHONY : src/write.cpp.o

src/write.i: src/write.cpp.i
.PHONY : src/write.i

# target to preprocess a source file
src/write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/write.cpp.i
.PHONY : src/write.cpp.i

src/write.s: src/write.cpp.s
.PHONY : src/write.s

# target to generate assembly for a file
src/write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_craft.dir/build.make CMakeFiles/code_craft.dir/src/write.cpp.s
.PHONY : src/write.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... code_craft"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/delete.o"
	@echo "... src/delete.i"
	@echo "... src/delete.s"
	@echo "... src/extern.o"
	@echo "... src/extern.i"
	@echo "... src/extern.s"
	@echo "... src/interactions.o"
	@echo "... src/interactions.i"
	@echo "... src/interactions.s"
	@echo "... src/read.o"
	@echo "... src/read.i"
	@echo "... src/read.s"
	@echo "... src/write.o"
	@echo "... src/write.i"
	@echo "... src/write.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

